server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: second-service
          uri: http://localhost:9094/
          predicates:
            - Path=/definition/**, /api/**
        - id: first-service
          uri: http://localhost:8080/
          predicates:
            - Path=/**
